# Generated by Django 2.2.5 on 2019-12-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abs_immigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('option_text', models.TextField(blank=True, null=True)),
                ('price_text', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
