# Generated by Django 2.2.5 on 2019-12-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_immigration', '0002_abs_immigration_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abs_immigration',
            name='featured',
            field=models.CharField(choices=[('M', 'Males'), ('F', 'Females')], max_length=10),
        ),
    ]
