# Generated by Django 2.2.5 on 2019-12-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_immigration', '0003_auto_20191216_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abs_immigration',
            name='featured',
            field=models.CharField(blank=True, choices=[('M', 'Males'), ('F', 'Females')], max_length=10),
        ),
    ]
