# Generated by Django 2.2.5 on 2019-12-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_immigration', '0004_auto_20191216_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abs_immigration',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='abs_immigration',
            name='price_text',
        ),
        migrations.AddField(
            model_name='abs_immigration',
            name='gender',
            field=models.CharField(choices=[('Males', 'Males'), ('Females', 'Females')], default='Males', max_length=10),
        ),
        migrations.AddField(
            model_name='abs_immigration',
            name='migration_type',
            field=models.CharField(choices=[(1, 'Arriving'), (2, 'Departing'), (3, 'Net Migration')], default='Arriving', max_length=10),
        ),
    ]
