# Generated by Django 2.2.5 on 2019-12-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_immigration', '0005_auto_20191216_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abs_immigration',
            name='gender',
            field=models.CharField(choices=[('Males', 'Males'), ('Females', 'Females'), ('Persons', 'Persons')], default='Males', max_length=10),
        ),
    ]
