# Generated by Django 2.0.7 on 2019-12-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_immigration', '0006_auto_20191216_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abs_immigration',
            name='migration_type',
            field=models.CharField(choices=[(1, 'Arriving'), (2, 'Departing'), (3, 'Net Migration')], max_length=10),
        ),
    ]
