# Generated by Django 2.0.7 on 2019-12-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_immigration', '0007_auto_20191216_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abs_immigration',
            name='migration_type',
            field=models.CharField(choices=[('Arriving', 'Arriving'), ('hi', 'Departing'), (3, 'Net Migration')], max_length=10),
        ),
    ]
