# Generated by Django 2.0.7 on 2019-12-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_immigration', '0008_auto_20191216_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abs_immigration',
            name='option_text',
        ),
        migrations.RemoveField(
            model_name='abs_immigration',
            name='title',
        ),
        migrations.AddField(
            model_name='abs_immigration',
            name='region',
            field=models.CharField(choices=[('Australia', 'Australia'), ('Victoria', 'Victoria')], default='Australia', max_length=100),
        ),
        migrations.AlterField(
            model_name='abs_immigration',
            name='gender',
            field=models.CharField(choices=[('Males', 'Males'), ('Females', 'Females'), ('Persons', 'Persons')], default='Persons', max_length=100),
        ),
        migrations.AlterField(
            model_name='abs_immigration',
            name='migration_type',
            field=models.CharField(choices=[('Arriving', 'Arriving'), ('hi', 'Departing'), ('Net Migration', 'Net Migration')], default='Arrival', max_length=100),
        ),
    ]
