# Generated by Django 2.0.7 on 2019-12-17 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abs_immigration', '0009_auto_20191216_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='abs_immigration',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abs_immigration',
            name='migration_type',
            field=models.CharField(choices=[('Arriving', 'Arriving'), ('Departing', 'Departing'), ('Net Migration', 'Net Migration')], default='Arrival', max_length=100),
        ),
    ]
